// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure;

#nullable disable

namespace Products.Infra.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250130150312_initseed")]
    partial class initseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 3, 11, 180, DateTimeKind.Utc).AddTicks(9843));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/85.png");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 3, 11, 181, DateTimeKind.Utc).AddTicks(230));

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 81,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enim ad est proident anim cillum ex ex sint fugiat nisi minim sunt enim. Elit pariatur elit eiusmod velit sit eu aliquip ipsum nisi. Dolor fugiat magna dolore esse aliquip magna eiusmod. Sint aliqua dolore eu officia exercitation ut in adipisicing. Cillum ut laborum deserunt incididunt qui in in voluptate Lorem sunt eiusmod dolore qui reprehenderit. Exercitation excepteur id ea minim fugiat qui magna exercitation labore Lorem.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Lavonne-Sharp",
                            Priority = 0,
                            Title = "Chasity Oliver"
                        },
                        new
                        {
                            Id = 52,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ea nisi reprehenderit anim id excepteur. Non adipisicing qui ex pariatur consectetur culpa id adipisicing anim anim laborum. Cillum aute pariatur amet dolor ullamco aliqua sit irure magna ad cillum ea. Incididunt veniam laborum reprehenderit aute occaecat irure nisi irure cupidatat non veniam irure veniam nisi. Tempor eiusmod enim anim quis et dolor minim anim cillum proident officia cillum. Nostrud ullamco excepteur minim id duis laboris. Cupidatat eiusmod do anim ad in laborum sint irure eu elit.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Carrie-Cooley",
                            Priority = 0,
                            Title = "Atkinson Ortiz"
                        },
                        new
                        {
                            Id = 16,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cupidatat ut in sit ex. Laboris incididunt est mollit id laboris est duis fugiat sunt dolore culpa consectetur. Nulla velit ut nostrud proident anim minim aliqua esse. Nisi cillum do aliqua reprehenderit est.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Lucinda-Patel",
                            Priority = 0,
                            Title = "Bond Dale"
                        },
                        new
                        {
                            Id = 117,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cillum sint labore anim ipsum exercitation. Laboris veniam ut minim consectetur laborum duis. Commodo exercitation sint nisi amet irure magna dolor est occaecat non do Lorem est. Labore velit et aliqua qui ea. In veniam labore excepteur cillum nulla dolor. Consequat id consectetur fugiat qui irure do cillum dolor pariatur. Nisi ea sit minim cupidatat sunt commodo culpa duis magna cupidatat sit eiusmod ipsum sint.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Rasmussen-Rutledge",
                            Priority = 0,
                            Title = "Alston Freeman"
                        },
                        new
                        {
                            Id = 84,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eu ullamco adipisicing nisi adipisicing consectetur. Mollit dolore ullamco nisi sunt occaecat officia. Nulla officia ea incididunt commodo amet. Tempor consectetur laboris eu aliquip et dolore officia.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Tyson-Hopper",
                            Priority = 0,
                            Title = "Maynard Anthony"
                        },
                        new
                        {
                            Id = 74,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ea sit proident laborum sint mollit minim culpa officia ut laborum consequat qui. Mollit amet labore do enim et cillum exercitation ullamco. Esse nulla eu incididunt et duis mollit.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Carmen-Vincent",
                            Priority = 0,
                            Title = "Amparo Walter"
                        },
                        new
                        {
                            Id = 101,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deserunt voluptate voluptate do ipsum magna elit velit fugiat ipsum. Eu non sunt pariatur excepteur aute eu. Elit adipisicing ipsum nostrud dolor. Ad labore elit laborum velit nulla aliquip dolor in aute nulla quis.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Burris-Dickerson",
                            Priority = 0,
                            Title = "Sanford Gould"
                        },
                        new
                        {
                            Id = 56,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Labore ipsum quis duis occaecat. Veniam laboris nostrud ad consectetur in. Ad ipsum consectetur adipisicing nulla irure aliquip eiusmod ad. Duis incididunt occaecat fugiat irure esse est id aliquip Lorem. Sint aliqua fugiat cillum ad excepteur deserunt enim non irure dolore qui. Commodo nisi dolore deserunt commodo voluptate occaecat consectetur tempor esse. Nulla ea ad nisi do eu qui dolore.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Sybil-Glass",
                            Priority = 0,
                            Title = "Jerry Haney"
                        },
                        new
                        {
                            Id = 156,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Et proident est voluptate labore velit non non velit. Ea exercitation irure enim do pariatur adipisicing do mollit. Velit nulla amet cupidatat voluptate eu incididunt excepteur labore sint. Eu commodo sit Lorem ea amet culpa et eu irure nisi.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Alyssa-Medina",
                            Priority = 0,
                            Title = "Lewis Becker"
                        });
                });

            modelBuilder.Entity("Products.domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 3, 11, 182, DateTimeKind.Utc).AddTicks(249));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 3, 11, 182, DateTimeKind.Utc).AddTicks(661));

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.HasOne("Products.domain.Categories.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.domain.Products.Product", b =>
                {
                    b.HasOne("Products.domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
