// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure;

#nullable disable

namespace Products.Infra.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 32, 41, 921, DateTimeKind.Utc).AddTicks(8679));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/85.png");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 32, 41, 921, DateTimeKind.Utc).AddTicks(9172));

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 81,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enim ad est proident anim cillum ex ex sint fugiat nisi minim sunt enim. Elit pariatur elit eiusmod velit sit eu aliquip ipsum nisi. Dolor fugiat magna dolore esse aliquip magna eiusmod. Sint aliqua dolore eu officia exercitation ut in adipisicing. Cillum ut laborum deserunt incididunt qui in in voluptate Lorem sunt eiusmod dolore qui reprehenderit. Exercitation excepteur id ea minim fugiat qui magna exercitation labore Lorem.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Lavonne-Sharp",
                            Priority = 0,
                            Title = "Chasity Oliver"
                        },
                        new
                        {
                            Id = 52,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ea nisi reprehenderit anim id excepteur. Non adipisicing qui ex pariatur consectetur culpa id adipisicing anim anim laborum. Cillum aute pariatur amet dolor ullamco aliqua sit irure magna ad cillum ea. Incididunt veniam laborum reprehenderit aute occaecat irure nisi irure cupidatat non veniam irure veniam nisi. Tempor eiusmod enim anim quis et dolor minim anim cillum proident officia cillum. Nostrud ullamco excepteur minim id duis laboris. Cupidatat eiusmod do anim ad in laborum sint irure eu elit.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Carrie-Cooley",
                            Priority = 0,
                            Title = "Atkinson Ortiz"
                        },
                        new
                        {
                            Id = 16,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cupidatat ut in sit ex. Laboris incididunt est mollit id laboris est duis fugiat sunt dolore culpa consectetur. Nulla velit ut nostrud proident anim minim aliqua esse. Nisi cillum do aliqua reprehenderit est.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Lucinda-Patel",
                            Priority = 0,
                            Title = "Bond Dale"
                        },
                        new
                        {
                            Id = 117,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cillum sint labore anim ipsum exercitation. Laboris veniam ut minim consectetur laborum duis. Commodo exercitation sint nisi amet irure magna dolor est occaecat non do Lorem est. Labore velit et aliqua qui ea. In veniam labore excepteur cillum nulla dolor. Consequat id consectetur fugiat qui irure do cillum dolor pariatur. Nisi ea sit minim cupidatat sunt commodo culpa duis magna cupidatat sit eiusmod ipsum sint.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Rasmussen-Rutledge",
                            Priority = 0,
                            Title = "Alston Freeman"
                        },
                        new
                        {
                            Id = 84,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eu ullamco adipisicing nisi adipisicing consectetur. Mollit dolore ullamco nisi sunt occaecat officia. Nulla officia ea incididunt commodo amet. Tempor consectetur laboris eu aliquip et dolore officia.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Tyson-Hopper",
                            Priority = 0,
                            Title = "Maynard Anthony"
                        },
                        new
                        {
                            Id = 74,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ea sit proident laborum sint mollit minim culpa officia ut laborum consequat qui. Mollit amet labore do enim et cillum exercitation ullamco. Esse nulla eu incididunt et duis mollit.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Carmen-Vincent",
                            Priority = 0,
                            Title = "Amparo Walter"
                        },
                        new
                        {
                            Id = 101,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deserunt voluptate voluptate do ipsum magna elit velit fugiat ipsum. Eu non sunt pariatur excepteur aute eu. Elit adipisicing ipsum nostrud dolor. Ad labore elit laborum velit nulla aliquip dolor in aute nulla quis.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Burris-Dickerson",
                            Priority = 0,
                            Title = "Sanford Gould"
                        },
                        new
                        {
                            Id = 56,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Labore ipsum quis duis occaecat. Veniam laboris nostrud ad consectetur in. Ad ipsum consectetur adipisicing nulla irure aliquip eiusmod ad. Duis incididunt occaecat fugiat irure esse est id aliquip Lorem. Sint aliqua fugiat cillum ad excepteur deserunt enim non irure dolore qui. Commodo nisi dolore deserunt commodo voluptate occaecat consectetur tempor esse. Nulla ea ad nisi do eu qui dolore.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Sybil-Glass",
                            Priority = 0,
                            Title = "Jerry Haney"
                        },
                        new
                        {
                            Id = 156,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Et proident est voluptate labore velit non non velit. Ea exercitation irure enim do pariatur adipisicing do mollit. Velit nulla amet cupidatat voluptate eu incididunt excepteur labore sint. Eu commodo sit Lorem ea amet culpa et eu irure nisi.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Alyssa-Medina",
                            Priority = 0,
                            Title = "Lewis Becker"
                        });
                });

            modelBuilder.Entity("Products.domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 32, 41, 922, DateTimeKind.Utc).AddTicks(8847));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 1, 30, 15, 32, 41, 922, DateTimeKind.Utc).AddTicks(9286));

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 37,
                            Active = true,
                            CategoryId = 16,
                            Code = "Romero",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cupidatat eiusmod duis in aliquip aute nisi incididunt cupidatat fugiat ea. Qui enim ut veniam et est qui laborum laboris velit deserunt aliquip ut consectetur fugiat. Nulla magna deserunt duis commodo nostrud cupidatat ullamco. Aliqua cupidatat non ullamco officia cillum enim dolore quis.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Rice-Foreman",
                            Price = 0m,
                            Title = "Lesley Sims"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CategoryId = 52,
                            Code = "Goff",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Minim dolor duis aliqua in mollit exercitation laborum magna exercitation. Dolor aute aliquip proident occaecat cupidatat labore non sit. Commodo ex deserunt amet voluptate.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Yang-Blackburn",
                            Price = 0m,
                            Title = "Irwin Cain"
                        },
                        new
                        {
                            Id = 67,
                            Active = true,
                            CategoryId = 56,
                            Code = "Whitehead",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adipisicing aliqua dolor tempor culpa do elit anim. Commodo adipisicing occaecat id dolor mollit cupidatat tempor laborum. Ea adipisicing eiusmod irure eu do consectetur officia id cillum.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Enid-Mcpherson",
                            Price = 0m,
                            Title = "Monica Gamble"
                        },
                        new
                        {
                            Id = 137,
                            Active = true,
                            CategoryId = 74,
                            Code = "Latasha",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Id eiusmod enim adipisicing ullamco minim excepteur pariatur reprehenderit mollit adipisicing aute qui. Ipsum exercitation laborum minim non deserunt sit adipisicing aliqua aliqua velit irure. Dolor adipisicing voluptate dolore qui ut occaecat pariatur eu. Magna aliquip velit aliqua velit ea aute labore ex aliqua. Reprehenderit fugiat sunt nisi in sint.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Randolph-Armstrong",
                            Price = 0m,
                            Title = "Pruitt Weiss"
                        },
                        new
                        {
                            Id = 53,
                            Active = false,
                            CategoryId = 81,
                            Code = "Hattie",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sint consequat nisi cupidatat aute exercitation officia eiusmod nisi laboris duis. Ipsum excepteur aliquip magna ut pariatur. Aliqua elit sint aute eiusmod nisi excepteur. Dolor ipsum adipisicing qui tempor ullamco magna tempor. Elit labore ipsum id deserunt excepteur ea ut. Id velit ipsum enim sit fugiat commodo deserunt commodo elit proident.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Brandi-Schroeder",
                            Price = 0m,
                            Title = "Yvette Allen"
                        },
                        new
                        {
                            Id = 165,
                            Active = false,
                            CategoryId = 84,
                            Code = "Butler",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nulla exercitation id aliqua nisi proident do sint adipisicing fugiat. Pariatur excepteur eu laborum qui eiusmod amet voluptate consectetur esse laborum mollit ea minim excepteur. Id do do nulla irure elit fugiat.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Maureen-Cleveland",
                            Price = 0m,
                            Title = "Serena Watts"
                        },
                        new
                        {
                            Id = 133,
                            Active = true,
                            CategoryId = 101,
                            Code = "Yates",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sit mollit mollit proident aute minim do culpa do laboris. Lorem fugiat officia quis dolor aliqua aliqua minim aliqua dolor nostrud pariatur quis id nisi. Adipisicing excepteur aute incididunt elit ex culpa do laborum pariatur cupidatat quis nisi nisi consequat. Ullamco labore irure magna dolore. Nisi ea mollit sunt in. Dolor fugiat consectetur nulla sit incididunt deserunt eiusmod id anim. Ullamco Lorem adipisicing eu sit excepteur elit laborum deserunt occaecat fugiat.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Morrow-Henderson",
                            Price = 0m,
                            Title = "Blackburn Chen"
                        },
                        new
                        {
                            Id = 90,
                            Active = false,
                            CategoryId = 156,
                            Code = "Irma",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enim non est ex laboris in cupidatat tempor aute proident laboris qui anim id. Enim deserunt et fugiat incididunt amet est eiusmod enim dolore id veniam. Ex quis ipsum nostrud ipsum eiusmod. Nostrud qui ea amet laborum do sit laborum. In cillum ut dolor amet ipsum tempor cillum deserunt labore Lorem. Velit ea sint amet laborum nulla nulla sit non quis et.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Andrews-Luna",
                            Price = 0m,
                            Title = "Gallegos Mcneil"
                        },
                        new
                        {
                            Id = 163,
                            Active = true,
                            CategoryId = 156,
                            Code = "Tisha",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sint magna consequat anim deserunt esse et dolore amet sint sunt. Enim ea eu est est elit veniam adipisicing. Sunt aliqua excepteur aliqua labore nisi culpa.",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Chrystal-Lewis",
                            Price = 0m,
                            Title = "Jolene Bradford"
                        });
                });

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.HasOne("Products.domain.Categories.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.domain.Products.Product", b =>
                {
                    b.HasOne("Products.domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.domain.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
